// Code Generated by Sidekick is for learning and experimentation purposes only.
import fs from 'fs';
import dotenv from 'dotenv';
import type { SafeEnvResult, SafeEnvConfig } from './types.js';

/**
 * Validates the environment variables against the documented example,
 * and loads them into process.env (like dotenv).
 */
export function config(options: SafeEnvConfig = {}): SafeEnvResult {
  const envPathSuffix = options.pathSuffix ?? '.example';

  const envPath = options.path || '.env';
  const examplePath = envPath + envPathSuffix;

  if (typeof envPath !== 'string' || envPath.trim() === '') {
    return { error: new Error('safeEnv: Invalid env file path provided'), parsed: undefined };
  }

  if (!fs.existsSync(envPath)) {
    return { error: new Error(`safeEnv: Env file not found at ${envPath}`), parsed: undefined };
  }
  if (!fs.existsSync(examplePath)) {
    return {
      error: new Error(
        `safeEnv: Documented env file not found at ${examplePath} (expected path based on ${envPath} with ${envPathSuffix} suffix)`
      ),
      parsed: undefined,
    };
  }

  const originalEnv = dotenv.config({ path: envPath });
  const documentedEnv = dotenv.config({ path: examplePath });

  const originalEnvParsed = originalEnv.parsed || {};
  const documentedEnvParsed = documentedEnv.parsed || {};

  // Gather missing / extra / same vars
  const missingInEnv = Object.keys(documentedEnvParsed).filter(key => !(key in originalEnvParsed));
  const undocumentedVars = Object.keys(originalEnvParsed).filter(key => !(key in documentedEnvParsed));
  const sameVars = Object.keys(documentedEnvParsed).filter(
    key => key in originalEnvParsed && originalEnvParsed[key] === documentedEnvParsed[key]
  );

  if (missingInEnv.length > 0) {
    return {
      error: new Error(`safeEnv: The following variables are documented but missing in ${envPath}: ${missingInEnv.join(', ')}`),
      parsed: undefined,
    };
  }
  if (undocumentedVars.length > 0) {
    return {
      error: new Error(
        `safeEnv: The following variables are present in ${envPath} but not documented in ${examplePath}: ${undocumentedVars.join(', ')}`
      ),
      parsed: undefined,
    };
  }
  if (sameVars.length > 0) {
    return {
      error: new Error(
        `safeEnv: The following variables have the same value in both ${envPath} and ${examplePath} (consider using placeholders/defaults in .env${envPathSuffix}): ${sameVars.join(
          ', '
        )}`
      ),
      parsed: undefined,
    };
  }

  // Mutate process.env like dotenv
  Object.assign(process.env, originalEnvParsed);
  return { error: undefined, parsed: originalEnvParsed };
}

/**
 * Allows validating/loading multiple env files at once.
 */
export function configMultiple(configs: SafeEnvConfig[] = []): SafeEnvResult[] {
  return configs.map(cfg => config(cfg));
}
